language: c

cache:
  directories:
  - $HOME/gnatsd

sudo: false

compiler: 
  - gcc
  - clang

addons:
  apt:
    packages:
    - valgrind
#    - libc6-dev-i386

before_install:
  - bash install_gnatsd.sh

before_script:
  - export PATH=$HOME/gnatsd:$PATH
  - mkdir build && cd build

env:
  - BUILD_OPT="-DNATS_BUILD_ARCH=64 -DNATS_BUILD_TYPE=Release"
  - BUILD_OPT="-DNATS_BUILD_ARCH=64 -DNATS_BUILD_TYPE=Release -DNATS_MEMCHECK_CMD=`which valgrind` -DNATS_SUPPRESSIONS_FILE=$TRAVIS_BUILD_DIR/test/valgrind_travis.sup" NATS_TEST_VALGRIND=yes CTEST_OPT="-T memcheck"

script:
  - cmake .. $BUILD_OPT && make rebuild_cache && make 
  - ctest --timeout 60 $CTEST_OPT 

notifications:
  email: false

